### ISSUE TITLE
What does the data in the posetrack_train_masks_in.json mean?

### ISSUE THREAD

**Issue by bridgeqiqi** [vita-epfl/decoupled-pose-prediction#3]
What does the data in the posetrack_train_masks_in.json mean? like 1.0 or 0.0? I feel confused about it. Could anyone help me understand it better? Thanks.

**Comment by bpfrd** [comment]
> 

Hi, this shows if the joints in the input frames are occluded or not. I think it becomes more clear to you if we look at the data in the json files:

import json
with open('somof_data_posetrack/posetrack_train_in.json', 'r') as f:
    poses_in = json.load(f)

poses_in has 306 examples (len(poses_in)=306), 
len(poses_in[0])=8 means there are 8 persons in the first example
len(poses_in[0][0])=16 means for the first person in the first example there are 16 frames
and finally len(poses_in[0][0][0])=28 these 28 numbers are the x and y coordinates of 14 joints, you can use it by .reshape(14, 2)

now let's see the posetrack_train_masks_in.json
with open('somof_data_posetrack/posetrack_train_masks_in.json', 'r') as f:
    masks_in = json.load(f)

len(masks_in)=306 corresponds to 306 examples, 
len(masks_in[0])=8 corresponds to 8 persons in the first example
len(masks_in[0][0])=16 corresponds to 16 input frames 
len(masks_in[0][0][0])=14 shows which joints in the posetrack_train_in.json are occluded (0) or not (1.)

I hope that helps.

best,

**Comment by bridgeqiqi** [comment]
Hi, thank you for your detailed response. so the masks are only used for computing the VIM metrics? By the way, what do the metrics (ade_c and fde_c) mean? In this paper, the VAM metric is also mentioned to evaluate the pose tracking performance, so how does it compute in your released code? Many thanks.

**Comment by bpfrd** [comment]
Hi, yes masks are used in the VIM metrics defined here: https://ieeexplore.ieee.org/document/9145701. ade and fde are extra metrics implemented. ade is the average displacement error and fde is the final displacement error. 

best, 
B

> Hi, thank you for your detailed response. so the masks are only used for computing the VIM metrics? By the way, what do the metrics (ade_c and fde_c) mean? In this paper, the VAM metric is also mentioned to evaluate the pose tracking performance, so how does it compute in your released code? Many thanks.
